name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      VITE_USE_MOCK_SERVICES: 'true'
      VITE_FIREBASE_API_KEY: 'demo-api-key'
      VITE_FIREBASE_AUTH_DOMAIN: 'demo-project.firebaseapp.com'
      VITE_FIREBASE_PROJECT_ID: 'demo-project'
      VITE_FIREBASE_STORAGE_BUCKET: 'demo-project.appspot.com'
      VITE_FIREBASE_MESSAGING_SENDER_ID: '123456789'
      VITE_FIREBASE_APP_ID: '1:123456789:web:abcdef123456'
      VITE_FLIGHT_API_PROVIDER: 'demo'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Direct Vite Build (Skip TS)
        run: npx vite build --config vite.config.build.js
      
      - name: List build output
        run: ls -la dist
      
      - name: Deploy to Firebase (Method 1)
        id: deploy1
        continue-on-error: true
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLIGHT_DASHBOARD_APP }}'
          channelId: live
          projectId: flight-dashboard-app
          
      - name: Deploy to Firebase (Method 2 - Fallback)
        if: steps.deploy1.outcome == 'failure'
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLIGHT_DASHBOARD_APP }}" > firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="./firebase-service-account.json"
          npm install -g firebase-tools@12.4.7
          firebase deploy --only hosting --project flight-dashboard-app --non-interactive